= OptaPlanner training lab 101
:awestruct-layout: base
:showtitle:


== Introduction

This training will help you become an OptaPlanner expert.

=== Prerequisites

* Basic understanding of Java development
* Basic understanding of DRL (drools rule language)

=== Preparation

. Open the http://docs.jboss.org/drools/release/latest/optaplanner-docs/html_single/index.html[the reference manual] in your browser.
. Unzip the +optaplanner-training-\*.zip+. This is a different zip than +optaplanner-distribution-\*.zip+.
. Open your favorite IDE (IntelliJ, Eclipse, NetBeans).

=== Troubleshooting

* If you have any trouble running the code in your favorite IDE,
http://docs.jboss.org/drools/release/latest/optaplanner-docs/html_single/index.html#runTheExamplesInAnIDE[read this].


== Part 1: Playing with the score function

Each business has specific constraints. In this part we will learn to cater for those constraints
by adjusting the score function accordingly.

=== Lab 101: No more than 4 processes per computer

The customer's use case is closely resembles the OptaPlanner example CloudBalancing.
But there's 1 big difference: No computer can have more than 4 processes assigned.

Preparation:

. Import as a new project in your favorite IDE: +optaplanner-training-lab101/pom.xml+
. Create a new run configuration:
.. Main class: org.optaplanner.examples.cloudbalancing.app.CloudBalancingApp
.. VM parameters (optional): +-Xmx512M -server+
.. Working directory: +optaplanner-training-lab101+ (this is the directory that contains the directory +data+)
. Run the run configuration.

Assignment:

. Add a new score rule in the file +cloudBalancingScoreRules.drl+

Solution:

[source,drl]
----
rule "atMost4ProcessesPerComputer"
  when
    $computer : CloudComputer()
    $count : Number(intValue > 4) from accumulate(
    $c : CloudProcess(computer == $computer),
      count($c)
    )
  then
    scoreHolder.addHardConstraintMatch(kcontext, 4 - $count.intValue());
end
----
