= OptaPlanner training
:awestruct-layout: base
:showtitle:


== Introduction

This training will help you become an OptaPlanner expert.
Count how many labs you can complete correctly without cheating :)

=== Prerequisites

* Basic understanding of Java development
* Basic understanding of DRL (drools rule language)

=== Preparation

. Open the http://docs.jboss.org/drools/release/latest/optaplanner-docs/html_single/index.html[the reference manual] in your browser.
. Unzip the +optaplanner-training-\*.zip+. This is a different zip than +optaplanner-distribution-\*.zip+.
. Open your favorite IDE (IntelliJ, Eclipse, NetBeans).

=== Troubleshooting

* If you have any trouble running the code in your favorite IDE,
http://docs.jboss.org/drools/release/latest/optaplanner-docs/html_single/index.html#runTheExamplesInAnIDE[read this].


== Part 1: Playing with the score function

Each business has specific constraints. In this part we will learn to cater for those constraints
by adjusting the score function accordingly.

include::lab101/lab101.adoc[]
