= OptaPlanner training
:showtitle:
:docinfo:

== Introduction

This training will help you become an OptaPlanner expert.
Count how many labs you can complete correctly without cheating :)

=== Prerequisites

* Basic understanding of Java development
* Basic understanding of DRL (drools rule language)

=== Preparation

. Open the http://docs.optaplanner.org/latest/optaplanner-docs/html_single/index.html[the reference manual] in your browser.
.. Read the chapter _Introduction_.
.. Read the chapter _Quick start_.
.. Read the table of contents (TOC). Grok the structure of the reference manual.
. Unzip the `optaplanner-training-\*.zip`. This is a different zip than `optaplanner-distribution-\*.zip`.
. Open your favorite IDE (IntelliJ, Eclipse, NetBeans).

=== Troubleshooting

* If you have any trouble running the code in your favorite IDE,
http://docs.optaplanner.org/latest/optaplanner-docs/html_single/index.html#runTheExamplesInAnIDE[read this].

== Part 0: What is a planning problem?

Print link:lab0/lab0.pdf[the exercises on paper] and complete them.
Verify your answers with the OptaPlanner examples:

* Open the NQueens example and quick open dataset `8queens`.
* Open the Traveling Salesman example and import dataset `tutorial/st68.tsp`.
  Right click to connect a location to the end of the trip.

== Part 1: Customizing the score function

Each business has specific constraints. In this part we will learn to cater for those constraints
by adjusting the score function accordingly.

include::lab1/lab100.adoc[]

include::lab1/lab101.adoc[]

include::lab1/lab102.adoc[]

include::lab1/lab103.adoc[]


== Part 2: Designing the model

The most difficult thing to learn is - by far - how to design a good domain model.
Which class is a planning entity? Which property is a planning variable?

include::lab2/lab200.adoc[]

include::lab2/lab201.adoc[]

include::lab2/lab202.adoc[]

include::lab2/lab203.adoc[]


== Part 3: Algorithm benchmarking and tweaking

TODO


== Part 4: Continuous and real-time planning

TODO

== Part 9: Putting it all together

Implement these use cases, given a domain model and data.

include::lab9/lab901.adoc[]

include::lab9/lab902.adoc[]
