= OptaPlanner training
:showtitle:
:docinfo:

== Introduction

This training will help you become an OptaPlanner expert.
Count how many labs you can complete correctly without cheating :)

=== Prerequisites

* Basic understanding of Java development
* Basic understanding of DRL (drools rule language)

=== Preparation

. Open the http://docs.jboss.org/optaplanner/release/latest/optaplanner-docs/html_single/index.html[the reference manual] in your browser.
.. Read the chapter _Introduction_.
.. Read the chapter _Quick start_.
.. Read the table of contents (TOC). Grok the structure of the reference manual.
. Unzip the `optaplanner-training-\*.zip`. This is a different zip than `optaplanner-distribution-\*.zip`.
. Open your favorite IDE (IntelliJ, Eclipse, NetBeans).

=== Troubleshooting

* If you have any trouble running the code in your favorite IDE,
http://docs.jboss.org/optaplanner/release/latest/optaplanner-docs/html_single/index.html#runTheExamplesInAnIDE[read this].


== Part 1: Customizing the score function

Each business has specific constraints. In this part we will learn to cater for those constraints
by adjusting the score function accordingly.

include::lab1/lab100.adoc[]

include::lab1/lab101.adoc[]

include::lab1/lab102.adoc[]

include::lab1/lab103.adoc[]


== Part 2: Designing the model

The most difficult thing to learn is - by far - how to design a good domain model.
Which class is a planning entity? Which property is a planning variable?
There are 2 guidelines:

* Normalize your domain model. Just as with any other domain model, prefer normalization whenever possible.
* In a `ManyToOne` relationship, the `Many` side is usually the planning entity which has a planning variable leading to the `One side.

include::lab2/lab201.adoc[]

include::lab2/lab202.adoc[]


== Part 3: Algorithm benchmarking and tweaking

TODO


== Part 4: Continuous and real-time planning

TODO
